--Usuarios(Nome,Apelido,Setor,DDD,Telefone)
--Equipes(um usuário só pode estar em uma equipe)
--Calendários(Cada equipe irá possuir um ou mais calendários)
--Eventos(Um evento tem que estar vinculado à algum calendário)

--Scaffold-DbContext "Server=(localdb)\MSSQLLocalDB;Database=KNEWIN_EVENT;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Entities -Force

CREATE DATABASE KNEWIN_EVENT
GO

USE KNEWIN_EVENT
GO

CREATE TABLE EQUIPE(
	COD_EQUIPE INT PRIMARY KEY,
	NOME VARCHAR(200) NOT NULL,
	ATIVO BIT DEFAULT 1
)
GO

CREATE TABLE USUARIO(
	COD_USUARIO INT PRIMARY KEY,
	NOME VARCHAR(200) NOT NULL,
	APELIDO VARCHAR(50),
	SETOR VARCHAR(100),
	DDD DECIMAL,
	TELEFONE VARCHAR(9),

	COD_EQUIPE INT
)
GO

ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_EQUIPE FOREIGN KEY (COD_EQUIPE)
	REFERENCES EQUIPE (COD_EQUIPE)
GO

CREATE TABLE CALENDARIO(
	COD_CALENDARIO INT PRIMARY KEY,
	NOME VARCHAR(200) NOT NULL,
	ATIVO BIT DEFAULT 1,

	COD_EQUIPE INT
)
GO

ALTER TABLE CALENDARIO ADD CONSTRAINT FK_CALENDARIO_EQUIPE FOREIGN KEY (COD_EQUIPE)
	REFERENCES EQUIPE (COD_EQUIPE)
GO

CREATE TABLE EVENTO(
	COD_EVENTO INT PRIMARY KEY,
	NOME VARCHAR(200) NOT NULL,
	ATIVO BIT DEFAULT 1,

	COD_CALENDARIO INT
)
GO

ALTER TABLE EVENTO ADD CONSTRAINT FK_EVENTO_CALENDARIO FOREIGN KEY (COD_CALENDARIO)
	REFERENCES CALENDARIO (COD_CALENDARIO)
GO

CREATE TABLE PRESENCA(
	COD_PRESENCA INT PRIMARY KEY,
	COD_EVENTO INT NOT NULL,
	COD_USUARIO INT NOT NULL
)
GO

ALTER TABLE PRESENCA ADD CONSTRAINT FK_PRESENCA_EVENTO FOREIGN KEY (COD_EVENTO)
	REFERENCES EVENTO (COD_EVENTO)
GO

ALTER TABLE PRESENCA ADD CONSTRAINT FK_PRESENCA_USUARIO FOREIGN KEY (COD_USUARIO)
	REFERENCES USUARIO (COD_USUARIO)
GO